/**
 * 
 */
package ca.mss.rd.trade.calypso.workflow;

import java.util.ArrayList;
import java.util.List;

import ca.mss.rd.trade.calypso.boprocess.mom.MessageType;
import ca.mss.rd.trade.calypso.refdata.trade.TradeAction;
import ca.mss.rd.trade.calypso.refdata.trade.TradeStatus;
import ca.mss.rd.trade.calypso.refdata.trade.product.ProductType;


/**
 * @author moskovsk
 *
 */
public class Workflow {

	final static public String className = Workflow.class.getName();
	final static public long serialVersionUID = className.hashCode();

	public List<WkfConfig> config;

	/**
	 * 
	 */
	public Workflow() {
		this.config = new ArrayList<WkfConfig>();
		populate();
	} 
	
	
	protected void populate(){
		config.add(new WkfConfig(300, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{WkfRuleTransfer.CheckContact}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(300, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{ WkfRuleTransfer.CheckContact}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(303, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(304, TradeStatus.PENDING, TradeAction.AUTHORIZE, TradeStatus.VERIFIED,false,true,false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(305, TradeStatus.PENDING, TradeAction.AMEND, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(306, TradeStatus.INVALID, TradeAction.AMEND, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(307, TradeStatus.VERIFIED, TradeAction.SEND, TradeStatus.SENT, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(308, TradeStatus.VERIFIED, TradeAction.HOLD, TradeStatus.HELD, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(309, TradeStatus.VERIFIED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(310, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{ WkfRuleTransfer.CheckCorrectContact}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(311, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(312, TradeStatus.INVALID, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(313, TradeStatus.VERIFIED, TradeAction.COPY, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(314, TradeStatus.HELD, TradeAction.AUTHORIZE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(315, TradeStatus.HELD, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(318, TradeStatus.SENT, TradeAction.ACK, TradeStatus.ACKED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(319, TradeStatus.SENT, TradeAction.NACK, TradeStatus.NACKED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(320, TradeStatus.INVALID, TradeAction.FIX, TradeStatus.PENDING,false,true,false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{ WkfRuleTransfer.ApplyDefaultContact},null,true,true,"","",false,1, false, false, false));
		config.add(new WkfConfig(326, TradeStatus.ACKED, TradeAction.MATCH, TradeStatus.MATCHED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(327, TradeStatus.ACKED, TradeAction.UNMATCH, TradeStatus.UNMATCHED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(328, TradeStatus.ACKED, TradeAction.MISMATCH, TradeStatus.MISMATCHED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(331, TradeStatus.NACKED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(332, TradeStatus.NACKED, TradeAction.SEND, TradeStatus.SENT, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(333, TradeStatus.NACKED, TradeAction.FIX, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(335, TradeStatus.VERIFIED, TradeAction.EDIT, TradeStatus.VERIFIED,true,false,false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(336, TradeStatus.PENDING, TradeAction.EDIT, TradeStatus.PENDING,true,false,false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(337, TradeStatus.ACKED, TradeAction.TRACE, TradeStatus.SENT, false, false, false, MessageType.ALL, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(18, TradeStatus.CREATED, TradeAction.PROCESS, TradeStatus.PROCESSED,false,true,false, MessageType.ACK_MSG, ProductType.ALL, new WkfRuleTransfer[]{ WkfRuleTransfer.HandleAckNack},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(17, TradeStatus.NONE, TradeAction.NEW, TradeStatus.CREATED, false, false, false, MessageType.ACK_MSG, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(8, TradeStatus.NONE, TradeAction.NEW, TradeStatus.TO_SEND, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(9, TradeStatus.TO_SEND, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(10, TradeStatus.TO_SEND, TradeAction.SEND, TradeStatus.SENT, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(11, TradeStatus.SENT, TradeAction.ACK, TradeStatus.UNMATCHED, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(12, TradeStatus.SENT, TradeAction.NACK, TradeStatus.NACKED, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(13, TradeStatus.NACKED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.CONFIRM, ProductType.ALL, new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99572, TradeStatus.AMENDED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER AMENDS THE TRADE","",false,0, false, false, false));
		config.add(new WkfConfig(99573, TradeStatus.AMENDED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99574, TradeStatus.AMENDED, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Trader will apply action to resubmit an amended trade back to MO","",false,0, false, false, false));
		config.add(new WkfConfig(99575, TradeStatus.AMENDED, TradeAction.TERM_APPROVAL, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Move trades with a credit event directly to pend_term.","",false,0, false, false, false));
		config.add(new WkfConfig(99576, TradeStatus.APPROVED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Jim Aug 30: Different User flag has been removed to accommodate the undo of partial termination; i.e. cancelling of remaining trades from approved status.","",false,0, false, false, false));
		config.add(new WkfConfig(99577, TradeStatus.APPROVED, TradeAction.ROLLBACK, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99578, TradeStatus.APPROVED, TradeAction.SECOND_APPROVAL, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBook,WkfRuleTransfer.CheckCCISCustomerCode,WkfRuleTransfer.CheckCounterPartyStatus,WkfRuleTransfer.CheckMultipleUpFrontFee,WkfRuleTransfer.ThreeParty}, null, false, true,"Second MO can approve the trade.  Only Trades with an approved counterparty can be verified.","",true,0, false, false, false));
		config.add(new WkfConfig(99579, TradeStatus.APPR_TERM, TradeAction.ROLLBACK, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99580, TradeStatus.APPR_TERM, TradeAction.SECOND_APPROVAL, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationFeeCCISCustomerCode,WkfRuleTransfer.ThreeParty}, null, false, true,"","",true,0, false, false, false));
		config.add(new WkfConfig(99581, TradeStatus.MATURED, TradeAction.AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99582, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{}, null, false, true,"New trades will go to pricing","",false,0, false, false, false));
		config.add(new WkfConfig(99583, TradeStatus.PENDING, TradeAction.AMEND, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99584, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(99585, TradeStatus.PENDING, TradeAction.FIRST_APPROVAL, TradeStatus.APPROVED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO user applies this action once the trader has put it in PENDING. It will require a second approval","",true,0, false, false, false));

		config.add(new WkfConfig(99586, TradeStatus.PENDING, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO will apply this action to hand back to FO","",false,0, false, false, false));
		config.add(new WkfConfig(99587, TradeStatus.PEND_TERM, TradeAction.FIRST_APPROVAL, TradeStatus.APPR_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO 1ST PERSON APPROVES TERMINATION","",true,0, false, false, false));
		config.add(new WkfConfig(99588, TradeStatus.PEND_TERM, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99589, TradeStatus.PEND_TERM, TradeAction.UNDO, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreePartyUndoTermination}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99590, TradeStatus.PRICING, TradeAction.AMEND, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Trader can change trade before executing","",true,0, false, false, false));
		config.add(new WkfConfig(99591, TradeStatus.PRICING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(99592, TradeStatus.PRICING, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Trader applies EXECUTE action commits the trade and submits to BO/MO approval","",false,0, false, false, false));
		config.add(new WkfConfig(99593, TradeStatus.PRICING, TradeAction.STP_PARTTERM, TradeStatus.PENDING,false,true,false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSTPRemainingTrade,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99594, TradeStatus.TERMINATED, TradeAction.AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99595, TradeStatus.TERMINATED, TradeAction.RECON_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(99596, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"When MO amends and there is PL impact  go to AMENDED for trader approval","",false,0, false, false, false));
		config.add(new WkfConfig(99597, TradeStatus.VERIFIED, TradeAction.CDX_DEFAULT_SETTLE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"FEE IS APPLIED TO THE TRADE AFTER CREDIT EVENT","",false,0, false, false, false));
		config.add(new WkfConfig(99598, TradeStatus.VERIFIED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckMature},null,false,false,"DONE THROUGH SCHEDULED TASK","",false,0, false, false, false));
		config.add(new WkfConfig(99599, TradeStatus.VERIFIED, TradeAction.RECON_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(99600, TradeStatus.VERIFIED, TradeAction.SET_CONFIRM, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99601, TradeStatus.VERIFIED, TradeAction.TERMINATE, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBackOfficeTerminate,WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER APPLIES THE TERMINATION THROUGH BO WINDOW.","",false,0, false, false, false));
		config.add(new WkfConfig(215088, TradeStatus.APPROVED, TradeAction.TERMINATE, TradeStatus.DUMMY_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Second MO can approve the trade.  Only Trades with an approved counterparty can be verified.","",false,0, false, false, false));

		config.add(new WkfConfig(216412, TradeStatus.DUMMY_TERM, TradeAction.AMEND, TradeStatus.DUMMY_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(229517, TradeStatus.DUMMY_TERM, TradeAction.TERM_FROM_DT, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233988, TradeStatus.MATURED, TradeAction.ACC_AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233989, TradeStatus.TERMINATED, TradeAction.ACC_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233990, TradeStatus.VERIFIED, TradeAction.ACC_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(535110, TradeStatus.VERIFIED, TradeAction.RECON_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(535111, TradeStatus.VERIFIED, TradeAction.TERMINATE, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBackOfficeTerminate,WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER APPLIES THE TERMINATION THROUGH BO WINDOW.","",false,0, false, false, false));
		config.add(new WkfConfig(535112, TradeStatus.APPR_TERM, TradeAction.ROLLBACK, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535113, TradeStatus.AMENDED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535115, TradeStatus.VERIFIED, TradeAction.SET_CONFIRM, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535119, TradeStatus.APPR_TERM, TradeAction.SECOND_APPROVAL, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationFeeCCISCustomerCode,WkfRuleTransfer.ThreeParty}, null, false, true,"","",true,0, false, false, false));
		config.add(new WkfConfig(535121, TradeStatus.PENDING, TradeAction.FIRST_APPROVAL, TradeStatus.APPROVED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO user applies this action once the trader has put it in PENDING. It will require a second approval","",true,0, false, false, false));

		config.add(new WkfConfig(535122, TradeStatus.PEND_TERM, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535123, TradeStatus.TERMINATED, TradeAction.RECON_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(535126, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{}, null, false, true,"New trades will go to pricing","",false,0, false, false, false));
		config.add(new WkfConfig(535127, TradeStatus.PENDING, TradeAction.AMEND, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535128, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(535129, TradeStatus.PRICING, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Trader applies EXECUTE action commits the trade and submits to BO/MO approval","",false,0, false, false, false));
		config.add(new WkfConfig(535130, TradeStatus.VERIFIED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckMature},null,false,false,"DONE THROUGH SCHEDULED TASK","",false,0, false, false, false));
		config.add(new WkfConfig(535132, TradeStatus.MATURED, TradeAction.AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535133, TradeStatus.PRICING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(535135, TradeStatus.TERMINATED, TradeAction.AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535136, TradeStatus.APPROVED, TradeAction.SECOND_APPROVAL, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBook,WkfRuleTransfer.CheckCCISCustomerCode,WkfRuleTransfer.CheckCounterPartyStatus,WkfRuleTransfer.CheckMultipleUpFrontFee,WkfRuleTransfer.ThreeParty}, null, false, true,"Second MO can approve the trade.  Only Trades with an approved counterparty can be verified.","",true,0, false, false, false));

		config.add(new WkfConfig(535137, TradeStatus.PEND_TERM, TradeAction.UNDO, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreePartyUndoTermination}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535138, TradeStatus.PENDING, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO will apply this action to hand back to FO","",false,0, false, false, false));
		config.add(new WkfConfig(535139, TradeStatus.AMENDED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER AMENDS THE TRADE","",false,0, false, false, false));
		config.add(new WkfConfig(535141, TradeStatus.AMENDED, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Trader will apply action to resubmit an amended trade back to MO","",false,0, false, false, false));
		config.add(new WkfConfig(535142, TradeStatus.APPROVED, TradeAction.ROLLBACK, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535143, TradeStatus.PEND_TERM, TradeAction.FIRST_APPROVAL, TradeStatus.APPR_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO 1ST PERSON APPROVES TERMINATION","",true,0, false, false, false));
		config.add(new WkfConfig(535144, TradeStatus.PRICING, TradeAction.AMEND, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Trader can change trade before executing","",true,0, false, false, false));
		config.add(new WkfConfig(535145, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"When MO amends and there is PL impact"," go to AMENDED for trader approval",false,0, false, false, false));
		config.add(new WkfConfig(535148, TradeStatus.APPROVED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Jim Aug 30: Different User flag has been removed to accomodatethe undo of partial termination; i.e. cancelling of remaining trades from approved status.","",false,0, false, false, false));
		config.add(new WkfConfig(535150, TradeStatus.PRICING, TradeAction.STP_PARTTERM, TradeStatus.PENDING,false,true,false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSTPRemainingTrade,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535151, TradeStatus.AMENDED, TradeAction.TERM_APPROVAL, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Move trades with a credit event directly to pend_term.","",false,0, false, false, false));
		config.add(new WkfConfig(535155, TradeStatus.TERMINATED, TradeAction.ACC_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535156, TradeStatus.MATURED, TradeAction.ACC_AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535157, TradeStatus.VERIFIED, TradeAction.ACC_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535158, TradeStatus.VERIFIED, TradeAction.EXERCISE, TradeStatus.PEND_EXERCISE, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535159, TradeStatus.PEND_EXERCISE, TradeAction.UNDO, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535160, TradeStatus.PEND_EXERCISE, TradeAction.FIRST_APPROVAL, TradeStatus.APPR_EXERCISE, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"","",true,0, false, false, false));
		config.add(new WkfConfig(535161, TradeStatus.APPR_EXERCISE, TradeAction.ROLLBACK, TradeStatus.PEND_EXERCISE, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535162, TradeStatus.APPR_EXERCISE, TradeAction.SECOND_APPROVAL, TradeStatus.EXERCISED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"","",true,0, false, false, false));
		config.add(new WkfConfig(535163, TradeStatus.EXERCISED, TradeAction.AMEND, TradeStatus.EXERCISED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535164, TradeStatus.VERIFIED, TradeAction.EXPIRE, TradeStatus.EXPIRED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(236270, TradeStatus.VERIFIED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(236271, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(236272, TradeStatus.MATURED, TradeAction.AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(236273, TradeStatus.NONE, TradeAction.NEW, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(423734, TradeStatus.MATURED, TradeAction.UNMATURE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99602, TradeStatus.AMENDED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER AMENDS THE TRADE","",false,0, false, false, false));
		config.add(new WkfConfig(99603, TradeStatus.AMENDED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99604, TradeStatus.AMENDED, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckNoTermCreditEvent,WkfRuleTransfer.CheckNoTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Trader will apply action to resubmit an amended trade back to MO","",false,0, false, false, false));
		config.add(new WkfConfig(99605, TradeStatus.AMENDED, TradeAction.TERM_APPROVAL, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true,"Move trades with a credit event directly to pend_term.","",false,0, false, false, false));
		config.add(new WkfConfig(99606, TradeStatus.APPROVED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"Jim Aug 30: Different User flag has been removed to accommodate the undo of partial termination; i.e. cancelling of remaining trades from approved status.","",false,0, false, false, false));
		config.add(new WkfConfig(99608, TradeStatus.APPROVED, TradeAction.ROLLBACK, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99609, TradeStatus.APPROVED, TradeAction.SECOND_APPROVAL, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBook,WkfRuleTransfer.CheckCCISCustomerCode,WkfRuleTransfer.CheckCounterPartyStatus,WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true,"Second MO can approve the trade.  Only Trades with an approved counterparty can be verified.","",true,0, false, false, false));
		config.add(new WkfConfig(99610, TradeStatus.APPR_TERM, TradeAction.ROLLBACK, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99611, TradeStatus.APPR_TERM, TradeAction.SECOND_APPROVAL, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationFeeCCISCustomerCode,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99613, TradeStatus.DEFAULTED, TradeAction.TERMINATE, TradeStatus.APPR_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99614, TradeStatus.MATURED, TradeAction.AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99615, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{}, null, false, true,"New trades will go to pricing","",false,0, false, false, false));
		config.add(new WkfConfig(99616, TradeStatus.PENDING, TradeAction.AMEND, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99617, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(99619, TradeStatus.PENDING, TradeAction.FIRST_APPROVAL, TradeStatus.APPROVED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true,"MO user applies this action once the trader has put it in PENDING. It will require a second approval","",true,0, false, false, false));
		config.add(new WkfConfig(99620, TradeStatus.PENDING, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO will apply this action to hand back to FO","",false,0, false, false, false));
		config.add(new WkfConfig(99621, TradeStatus.PEND_TERM, TradeAction.FIRST_APPROVAL, TradeStatus.APPR_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true,"MO 1ST PERSON APPROVES TERMINATION","",true,0, false, false, false));
		config.add(new WkfConfig(99622, TradeStatus.PEND_TERM, TradeAction.ROLLBACK, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckTerminationKeyword,WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99623, TradeStatus.PEND_TERM, TradeAction.UNDO, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreePartyUndoTermination}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99624, TradeStatus.PRICING, TradeAction.AMEND, TradeStatus.PRICING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true,"Trader can change trade before executing","",true,0, false, false, false));
		config.add(new WkfConfig(99625, TradeStatus.PRICING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false,"Tear-up. Trade is abandoned or re-keyed.","",false,0, false, false, false));
		config.add(new WkfConfig(99626, TradeStatus.PRICING, TradeAction.EXECUTE, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true,"Trader applies EXECUTE action commits the trade and submits to BO/MO approval","",false,0, false, false, false));
		config.add(new WkfConfig(99627, TradeStatus.PRICING, TradeAction.STP_PARTTERM, TradeStatus.PENDING,false,true,false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSTPRemainingTrade,WkfRuleTransfer.ThreeParty}, null, false, true,"Move generated trades due to partial term into Pending","",false,0, false, false, false));
		config.add(new WkfConfig(99628, TradeStatus.TERMINATED, TradeAction.AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99629, TradeStatus.TERMINATED, TradeAction.RECON_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(99630, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.AMENDED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckHedgeAmount,WkfRuleTransfer.ThreeParty}, null, false, true,"When MO amends and there is PL impact, go to AMENDED for trader approval","",false,0, false, false, false));
		config.add(new WkfConfig(99631, TradeStatus.VERIFIED, TradeAction.CDS_DEFAULT, TradeStatus.DEFAULTED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99633, TradeStatus.VERIFIED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckMature},null,false,false,"DONE THROUGH SCHEDULED TASK","",false,0, false, false, false));
		config.add(new WkfConfig(99634, TradeStatus.VERIFIED, TradeAction.RECON_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"This action is for reconciliation purposes only.","",false,0, false, false, false));
		config.add(new WkfConfig(99635, TradeStatus.VERIFIED, TradeAction.SET_CONFIRM, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99636, TradeStatus.VERIFIED, TradeAction.TERMINATE, TradeStatus.PEND_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBackOfficeTerminate,WkfRuleTransfer.ThreeParty}, null, false, true,"TRADER APPLIES THE TERMINATION THROUGH BO WINDOW.","",false,0, false, false, false));
		config.add(new WkfConfig(202392, TradeStatus.TERMINATED, TradeAction.TERMINATE, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckBackOfficeTerminate,WkfRuleTransfer.ThreeParty},null,false,false,"TRADER APPLIES THE TERMINATON THROUGH BO WINDOW","",false,0, false, false, false));
		config.add(new WkfConfig(204619, TradeStatus.TERMINATED, TradeAction.UNDO, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(206741, TradeStatus.DEFAULTED, TradeAction.AMEND, TradeStatus.DEFAULTED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(210759, TradeStatus.APPROVED, TradeAction.TERMINATE, TradeStatus.DUMMY_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(210760, TradeStatus.DUMMY_TERM, TradeAction.AMEND, TradeStatus.DUMMY_TERM, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(216280, TradeStatus.APPROVED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(217350, TradeStatus.APPROVED, TradeAction.CDS__DEFAULT_DUM, TradeStatus.DEFAULTED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(218248, TradeStatus.DUMMY_TERM, TradeAction.UNDUMMY_TERM, TradeStatus.APPROVED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(229489, TradeStatus.DUMMY_TERM, TradeAction.OFFICAL_TERM, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false,"To be used only for clean up of NY Arb trades terminated","",false,0, false, false, false));
		config.add(new WkfConfig(233984, TradeStatus.VERIFIED, TradeAction.ACC_AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233985, TradeStatus.TERMINATED, TradeAction.ACC_AMEND, TradeStatus.TERMINATED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233986, TradeStatus.DEFAULTED, TradeAction.ACC_AMEND, TradeStatus.DEFAULTED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(233987, TradeStatus.MATURED, TradeAction.ACC_AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.ThreeParty},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99637, TradeStatus.MATURED, TradeAction.AMEND, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.Loan,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99638, TradeStatus.NONE, TradeAction.NEW, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.Loan,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99639, TradeStatus.VERIFIED, TradeAction.AMEND, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.Loan,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99640, TradeStatus.VERIFIED, TradeAction.MATURE, TradeStatus.MATURED, false, false, false, MessageType.ALL, ProductType.Loan,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99642, TradeStatus.AMT_AUTHORIZE, TradeAction.AUTHORIZE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99643, TradeStatus.AMT_AUTHORIZE, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99644, TradeStatus.CANCELED, TradeAction.UPDATE, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99645, TradeStatus.INVALID, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99646, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99647, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckCorrectSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99648, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99649, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.AMT_AUTHORIZE,false,true,false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtGreater500000,WkfRuleTransfer.CheckKickOff},null,true,true,"","",false,1, false, false, false));
		config.add(new WkfConfig(99651, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.VERIFIED,false,true,false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtLower500000,WkfRuleTransfer.CheckKickOff},null,true,false,"","",false,1, false, false, false));
		config.add(new WkfConfig(99653, TradeStatus.VERIFIED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99654, TradeStatus.VERIFIED, TradeAction.INVALID, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99655, TradeStatus.VERIFIED, TradeAction.SETTLE, TradeStatus.SETTLED, false, false, false, MessageType.ALL, ProductType.CDSIndex,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(535114, TradeStatus.AMT_AUTHORIZE, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535116, TradeStatus.AMT_AUTHORIZE, TradeAction.AUTHORIZE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535117, TradeStatus.CANCELED, TradeAction.UPDATE, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535118, TradeStatus.VERIFIED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535124, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.VERIFIED,false,true,false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtLower500000,WkfRuleTransfer.CheckKickOff},null,true,false,"","",false,1, false, false, false));
		config.add(new WkfConfig(535125, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535131, TradeStatus.INVALID, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535134, TradeStatus.VERIFIED, TradeAction.SETTLE, TradeStatus.SETTLED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535140, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.AMT_AUTHORIZE,false,true,false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtGreater500000,WkfRuleTransfer.CheckKickOff},null,true,true,"","",false,1, false, false, false));
		config.add(new WkfConfig(535146, TradeStatus.VERIFIED, TradeAction.INVALID, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535147, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckCorrectSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(535149, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CDSIndexOption,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(0, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CreditArrangement,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSDI}, null, false, true, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99656, TradeStatus.AMT_AUTHORIZE, TradeAction.AUTHORIZE, TradeStatus.VERIFIED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99657, TradeStatus.AMT_AUTHORIZE, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99658, TradeStatus.CANCELED, TradeAction.UPDATE, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99659, TradeStatus.INVALID, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99660, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99661, TradeStatus.NONE, TradeAction.NEW, TradeStatus.PENDING, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckCorrectSDI}, null, false, true, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99662, TradeStatus.PENDING, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99663, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.AMT_AUTHORIZE,false,true,false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtGreater10m,WkfRuleTransfer.CheckKickOff},null,true,true,"","",false,1, false, false, false));
		config.add(new WkfConfig(99665, TradeStatus.PENDING, TradeAction.EXECUTE, TradeStatus.VERIFIED,false,true,false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckAmtLower10m,WkfRuleTransfer.CheckKickOff},null,true,false,"","",false,1, false, false, false));
		config.add(new WkfConfig(99667, TradeStatus.VERIFIED, TradeAction.CANCEL, TradeStatus.CANCELED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99668, TradeStatus.VERIFIED, TradeAction.INVALID, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));
		config.add(new WkfConfig(99669, TradeStatus.VERIFIED, TradeAction.SETTLE, TradeStatus.SETTLED, false, false, false, MessageType.ALL, ProductType.CreditDefaultSwap,new WkfRuleTransfer[]{},null,false,false, "", "", false, 0, false, false, false));


		config.add(new WkfConfig(99670, TradeStatus.NONE, TradeAction.NEW, TradeStatus.INVALID, false, false, false, MessageType.ALL, ProductType.Loan,new WkfRuleTransfer[]{ WkfRuleTransfer.CheckSDI}, null, false, true, "", "", false, 0, false, false, false));
	}
	
}


