//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for autoRetryConfiguration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="autoRetryConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delayBetweenAttemptsInMs" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="maximumNumberOfRetryAttempts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maximumRetryDurationInMs" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "autoRetryConfiguration", propOrder = {
    "delayBetweenAttemptsInMs",
    "maximumNumberOfRetryAttempts",
    "maximumRetryDurationInMs"
})
public class AutoRetryConfiguration {

    protected long delayBetweenAttemptsInMs;
    protected int maximumNumberOfRetryAttempts;
    protected long maximumRetryDurationInMs;

    /**
     * Gets the value of the delayBetweenAttemptsInMs property.
     * 
     */
    public long getDelayBetweenAttemptsInMs() {
        return delayBetweenAttemptsInMs;
    }

    /**
     * Sets the value of the delayBetweenAttemptsInMs property.
     * 
     */
    public void setDelayBetweenAttemptsInMs(long value) {
        this.delayBetweenAttemptsInMs = value;
    }

    /**
     * Gets the value of the maximumNumberOfRetryAttempts property.
     * 
     */
    public int getMaximumNumberOfRetryAttempts() {
        return maximumNumberOfRetryAttempts;
    }

    /**
     * Sets the value of the maximumNumberOfRetryAttempts property.
     * 
     */
    public void setMaximumNumberOfRetryAttempts(int value) {
        this.maximumNumberOfRetryAttempts = value;
    }

    /**
     * Gets the value of the maximumRetryDurationInMs property.
     * 
     */
    public long getMaximumRetryDurationInMs() {
        return maximumRetryDurationInMs;
    }

    /**
     * Sets the value of the maximumRetryDurationInMs property.
     * 
     */
    public void setMaximumRetryDurationInMs(long value) {
        this.maximumRetryDurationInMs = value;
    }

}
