//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Execution Definition which generates checksums for one or multiple files.
 * 
 * <p>Java class for checksumGeneration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="checksumGeneration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourceResource" type="{}resource"/>
 *         &lt;element name="markerResource" type="{}resource"/>
 *         &lt;element name="checksumAlgorithm" type="{}checksumAlgorithmTypeEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checksumGeneration", propOrder = {
    "sourceResource",
    "markerResource",
    "checksumAlgorithm"
})
public class ChecksumGeneration {

    @XmlElement(required = true)
    protected Resource sourceResource;
    @XmlElement(required = true)
    protected Resource markerResource;
    @XmlElement(required = true)
    protected ChecksumAlgorithmTypeEnum checksumAlgorithm;

    /**
     * Gets the value of the sourceResource property.
     * 
     * @return
     *     possible object is
     *     {@link Resource }
     *     
     */
    public Resource getSourceResource() {
        return sourceResource;
    }

    /**
     * Sets the value of the sourceResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource }
     *     
     */
    public void setSourceResource(Resource value) {
        this.sourceResource = value;
    }

    /**
     * Gets the value of the markerResource property.
     * 
     * @return
     *     possible object is
     *     {@link Resource }
     *     
     */
    public Resource getMarkerResource() {
        return markerResource;
    }

    /**
     * Sets the value of the markerResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource }
     *     
     */
    public void setMarkerResource(Resource value) {
        this.markerResource = value;
    }

    /**
     * Gets the value of the checksumAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link ChecksumAlgorithmTypeEnum }
     *     
     */
    public ChecksumAlgorithmTypeEnum getChecksumAlgorithm() {
        return checksumAlgorithm;
    }

    /**
     * Sets the value of the checksumAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChecksumAlgorithmTypeEnum }
     *     
     */
    public void setChecksumAlgorithm(ChecksumAlgorithmTypeEnum value) {
        this.checksumAlgorithm = value;
    }

}
