//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Execution Definition.  Defines the work to be performed by the Batch Stage Processor for this Stage of the Workflow.
 * 
 * <p>Java class for execDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="execDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}noOpExecDefinition"/>
 *         &lt;element ref="{}dbFunction"/>
 *         &lt;element ref="{}dbProcedure"/>
 *         &lt;element ref="{}pollingFileWatcher"/>
 *         &lt;element ref="{}fileTransfer"/>
 *         &lt;element ref="{}deleteResource"/>
 *         &lt;element ref="{}checksumValidation"/>
 *         &lt;element ref="{}checksumGeneration"/>
 *         &lt;element ref="{}callExternalProcess"/>
 *         &lt;element ref="{}sqlLoader"/>
 *         &lt;element ref="{}javaExtension"/>
 *         &lt;element ref="{}callActiviti"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "execDefinition", propOrder = {
    "noOpExecDefinition",
    "dbFunction",
    "dbProcedure",
    "pollingFileWatcher",
    "fileTransfer",
    "deleteResource",
    "checksumValidation",
    "checksumGeneration",
    "callExternalProcess",
    "sqlLoader",
    "javaExtension",
    "callActiviti"
})
public class ExecDefinition {

    protected NoOpExecDefinition noOpExecDefinition;
    protected DbFunction dbFunction;
    protected DbProcedure dbProcedure;
    protected PollingFileWatcher pollingFileWatcher;
    protected FileTransfer fileTransfer;
    protected DeleteResource deleteResource;
    protected ChecksumValidation checksumValidation;
    protected ChecksumGeneration checksumGeneration;
    protected CallExternalProcess callExternalProcess;
    protected SqlLoader sqlLoader;
    protected JavaExtension javaExtension;
    protected CallActiviti callActiviti;

    /**
     * Gets the value of the noOpExecDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link NoOpExecDefinition }
     *     
     */
    public NoOpExecDefinition getNoOpExecDefinition() {
        return noOpExecDefinition;
    }

    /**
     * Sets the value of the noOpExecDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoOpExecDefinition }
     *     
     */
    public void setNoOpExecDefinition(NoOpExecDefinition value) {
        this.noOpExecDefinition = value;
    }

    /**
     * Gets the value of the dbFunction property.
     * 
     * @return
     *     possible object is
     *     {@link DbFunction }
     *     
     */
    public DbFunction getDbFunction() {
        return dbFunction;
    }

    /**
     * Sets the value of the dbFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbFunction }
     *     
     */
    public void setDbFunction(DbFunction value) {
        this.dbFunction = value;
    }

    /**
     * Gets the value of the dbProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link DbProcedure }
     *     
     */
    public DbProcedure getDbProcedure() {
        return dbProcedure;
    }

    /**
     * Sets the value of the dbProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbProcedure }
     *     
     */
    public void setDbProcedure(DbProcedure value) {
        this.dbProcedure = value;
    }

    /**
     * Gets the value of the pollingFileWatcher property.
     * 
     * @return
     *     possible object is
     *     {@link PollingFileWatcher }
     *     
     */
    public PollingFileWatcher getPollingFileWatcher() {
        return pollingFileWatcher;
    }

    /**
     * Sets the value of the pollingFileWatcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link PollingFileWatcher }
     *     
     */
    public void setPollingFileWatcher(PollingFileWatcher value) {
        this.pollingFileWatcher = value;
    }

    /**
     * Gets the value of the fileTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link FileTransfer }
     *     
     */
    public FileTransfer getFileTransfer() {
        return fileTransfer;
    }

    /**
     * Sets the value of the fileTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileTransfer }
     *     
     */
    public void setFileTransfer(FileTransfer value) {
        this.fileTransfer = value;
    }

    /**
     * Gets the value of the deleteResource property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteResource }
     *     
     */
    public DeleteResource getDeleteResource() {
        return deleteResource;
    }

    /**
     * Sets the value of the deleteResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteResource }
     *     
     */
    public void setDeleteResource(DeleteResource value) {
        this.deleteResource = value;
    }

    /**
     * Gets the value of the checksumValidation property.
     * 
     * @return
     *     possible object is
     *     {@link ChecksumValidation }
     *     
     */
    public ChecksumValidation getChecksumValidation() {
        return checksumValidation;
    }

    /**
     * Sets the value of the checksumValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChecksumValidation }
     *     
     */
    public void setChecksumValidation(ChecksumValidation value) {
        this.checksumValidation = value;
    }

    /**
     * Gets the value of the checksumGeneration property.
     * 
     * @return
     *     possible object is
     *     {@link ChecksumGeneration }
     *     
     */
    public ChecksumGeneration getChecksumGeneration() {
        return checksumGeneration;
    }

    /**
     * Sets the value of the checksumGeneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChecksumGeneration }
     *     
     */
    public void setChecksumGeneration(ChecksumGeneration value) {
        this.checksumGeneration = value;
    }

    /**
     * Gets the value of the callExternalProcess property.
     * 
     * @return
     *     possible object is
     *     {@link CallExternalProcess }
     *     
     */
    public CallExternalProcess getCallExternalProcess() {
        return callExternalProcess;
    }

    /**
     * Sets the value of the callExternalProcess property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallExternalProcess }
     *     
     */
    public void setCallExternalProcess(CallExternalProcess value) {
        this.callExternalProcess = value;
    }

    /**
     * Gets the value of the sqlLoader property.
     * 
     * @return
     *     possible object is
     *     {@link SqlLoader }
     *     
     */
    public SqlLoader getSqlLoader() {
        return sqlLoader;
    }

    /**
     * Sets the value of the sqlLoader property.
     * 
     * @param value
     *     allowed object is
     *     {@link SqlLoader }
     *     
     */
    public void setSqlLoader(SqlLoader value) {
        this.sqlLoader = value;
    }

    /**
     * Gets the value of the javaExtension property.
     * 
     * @return
     *     possible object is
     *     {@link JavaExtension }
     *     
     */
    public JavaExtension getJavaExtension() {
        return javaExtension;
    }

    /**
     * Sets the value of the javaExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaExtension }
     *     
     */
    public void setJavaExtension(JavaExtension value) {
        this.javaExtension = value;
    }

    /**
     * Gets the value of the callActiviti property.
     * 
     * @return
     *     possible object is
     *     {@link CallActiviti }
     *     
     */
    public CallActiviti getCallActiviti() {
        return callActiviti;
    }

    /**
     * Sets the value of the callActiviti property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallActiviti }
     *     
     */
    public void setCallActiviti(CallActiviti value) {
        this.callActiviti = value;
    }

}
