//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Execution Definition which executes a custom Java extension.  The Java extension must be available on the Batch Stage Processor's classpath, and implement IMaestroJavaExtensionExecutor.
 * 
 * <p>Java class for javaExtension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="javaExtension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="javaExtensionExecutorClassName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element ref="{}simpleProperties"/>
 *           &lt;element ref="{}cdataProperties"/>
 *         &lt;/choice>
 *         &lt;element name="javaExtensionOutputPropertyNames" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="propertyName" maxOccurs="99" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="255"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="outputPropertyMapping" type="{}propertyMapping" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "javaExtension", propOrder = {
    "javaExtensionExecutorClassName",
    "simpleProperties",
    "cdataProperties",
    "javaExtensionOutputPropertyNames",
    "outputPropertyMapping"
})
public class JavaExtension {

    @XmlElement(required = true)
    protected String javaExtensionExecutorClassName;
    protected SimpleProperties simpleProperties;
    protected CdataProperties cdataProperties;
    protected JavaExtension.JavaExtensionOutputPropertyNames javaExtensionOutputPropertyNames;
    protected PropertyMapping outputPropertyMapping;

    /**
     * Gets the value of the javaExtensionExecutorClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaExtensionExecutorClassName() {
        return javaExtensionExecutorClassName;
    }

    /**
     * Sets the value of the javaExtensionExecutorClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaExtensionExecutorClassName(String value) {
        this.javaExtensionExecutorClassName = value;
    }

    /**
     * Gets the value of the simpleProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleProperties }
     *     
     */
    public SimpleProperties getSimpleProperties() {
        return simpleProperties;
    }

    /**
     * Sets the value of the simpleProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleProperties }
     *     
     */
    public void setSimpleProperties(SimpleProperties value) {
        this.simpleProperties = value;
    }

    /**
     * Gets the value of the cdataProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CdataProperties }
     *     
     */
    public CdataProperties getCdataProperties() {
        return cdataProperties;
    }

    /**
     * Sets the value of the cdataProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdataProperties }
     *     
     */
    public void setCdataProperties(CdataProperties value) {
        this.cdataProperties = value;
    }

    /**
     * Gets the value of the javaExtensionOutputPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link JavaExtension.JavaExtensionOutputPropertyNames }
     *     
     */
    public JavaExtension.JavaExtensionOutputPropertyNames getJavaExtensionOutputPropertyNames() {
        return javaExtensionOutputPropertyNames;
    }

    /**
     * Sets the value of the javaExtensionOutputPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaExtension.JavaExtensionOutputPropertyNames }
     *     
     */
    public void setJavaExtensionOutputPropertyNames(JavaExtension.JavaExtensionOutputPropertyNames value) {
        this.javaExtensionOutputPropertyNames = value;
    }

    /**
     * Gets the value of the outputPropertyMapping property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyMapping }
     *     
     */
    public PropertyMapping getOutputPropertyMapping() {
        return outputPropertyMapping;
    }

    /**
     * Sets the value of the outputPropertyMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyMapping }
     *     
     */
    public void setOutputPropertyMapping(PropertyMapping value) {
        this.outputPropertyMapping = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="propertyName" maxOccurs="99" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="255"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "propertyName"
    })
    public static class JavaExtensionOutputPropertyNames {

        protected List<String> propertyName;

        /**
         * Gets the value of the propertyName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the propertyName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPropertyName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPropertyName() {
            if (propertyName == null) {
                propertyName = new ArrayList<String>();
            }
            return this.propertyName;
        }

    }

}
