//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.mss.rd.wkfdef.iw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ComponentReference_QNAME = new QName("", "componentReference");
    private final static QName _AutoRetryConfiguration_QNAME = new QName("", "autoRetryConfiguration");
    private final static QName _DeleteResource_QNAME = new QName("", "deleteResource");
    private final static QName _JavaExtension_QNAME = new QName("", "javaExtension");
    private final static QName _Param_QNAME = new QName("", "param");
    private final static QName _CallActiviti_QNAME = new QName("", "callActiviti");
    private final static QName _SimpleProperty_QNAME = new QName("", "simpleProperty");
    private final static QName _Mapping_QNAME = new QName("", "mapping");
    private final static QName _ExecDefinition_QNAME = new QName("", "execDefinition");
    private final static QName _Stage_QNAME = new QName("", "stage");
    private final static QName _Sequential_QNAME = new QName("", "sequential");
    private final static QName _WorkflowComponent_QNAME = new QName("", "workflowComponent");
    private final static QName _PollingFileWatcher_QNAME = new QName("", "pollingFileWatcher");
    private final static QName _ExternalWorkflowReference_QNAME = new QName("", "externalWorkflowReference");
    private final static QName _ProcessDefinitionId_QNAME = new QName("", "processDefinitionId");
    private final static QName _FileTransfer_QNAME = new QName("", "fileTransfer");
    private final static QName _SimpleProperties_QNAME = new QName("", "simpleProperties");
    private final static QName _Parallel_QNAME = new QName("", "parallel");
    private final static QName _Transfer_QNAME = new QName("", "transfer");
    private final static QName _StageFailure_QNAME = new QName("", "stageFailure");
    private final static QName _ProcessDescriptor_QNAME = new QName("", "processDescriptor");
    private final static QName _Resource_QNAME = new QName("", "resource");
    private final static QName _CallExternalProcess_QNAME = new QName("", "callExternalProcess");
    private final static QName _PropertyMapping_QNAME = new QName("", "propertyMapping");
    private final static QName _Property_QNAME = new QName("", "property");
    private final static QName _NoOpExecDefinition_QNAME = new QName("", "noOpExecDefinition");
    private final static QName _Properties_QNAME = new QName("", "properties");
    private final static QName _ChecksumValidation_QNAME = new QName("", "checksumValidation");
    private final static QName _Workflow_QNAME = new QName("", "workflow");
    private final static QName _CdataProperties_QNAME = new QName("", "cdataProperties");
    private final static QName _ChecksumGeneration_QNAME = new QName("", "checksumGeneration");
    private final static QName _SqlLoader_QNAME = new QName("", "sqlLoader");
    private final static QName _DbProcedure_QNAME = new QName("", "dbProcedure");
    private final static QName _DbFunction_QNAME = new QName("", "dbFunction");
    private final static QName _Variable_QNAME = new QName("", "variable");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.mss.rd.wkfdef.iw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DbFunction }
     * 
     */
    public DbFunction createDbFunction() {
        return new DbFunction();
    }

    /**
     * Create an instance of {@link DbProcedure }
     * 
     */
    public DbProcedure createDbProcedure() {
        return new DbProcedure();
    }

    /**
     * Create an instance of {@link WorkflowDefinition }
     * 
     */
    public WorkflowDefinition createWorkflowDefinition() {
        return new WorkflowDefinition();
    }

    /**
     * Create an instance of {@link WorkflowProperties }
     * 
     */
    public WorkflowProperties createWorkflowProperties() {
        return new WorkflowProperties();
    }

    /**
     * Create an instance of {@link SimpleProperties }
     * 
     */
    public SimpleProperties createSimpleProperties() {
        return new SimpleProperties();
    }

    /**
     * Create an instance of {@link ExternalWorkflowReference }
     * 
     */
    public ExternalWorkflowReference createExternalWorkflowReference() {
        return new ExternalWorkflowReference();
    }

    /**
     * Create an instance of {@link PollingFileWatcher }
     * 
     */
    public PollingFileWatcher createPollingFileWatcher() {
        return new PollingFileWatcher();
    }

    /**
     * Create an instance of {@link CallActiviti }
     * 
     */
    public CallActiviti createCallActiviti() {
        return new CallActiviti();
    }

    /**
     * Create an instance of {@link JavaExtension }
     * 
     */
    public JavaExtension createJavaExtension() {
        return new JavaExtension();
    }

    /**
     * Create an instance of {@link ComponentReference }
     * 
     */
    public ComponentReference createComponentReference() {
        return new ComponentReference();
    }

    /**
     * Create an instance of {@link AutoRetryConfiguration }
     * 
     */
    public AutoRetryConfiguration createAutoRetryConfiguration() {
        return new AutoRetryConfiguration();
    }

    /**
     * Create an instance of {@link DeleteResource }
     * 
     */
    public DeleteResource createDeleteResource() {
        return new DeleteResource();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link SimpleProperty }
     * 
     */
    public SimpleProperty createSimpleProperty() {
        return new SimpleProperty();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link ExecDefinition }
     * 
     */
    public ExecDefinition createExecDefinition() {
        return new ExecDefinition();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link Sequential }
     * 
     */
    public Sequential createSequential() {
        return new Sequential();
    }

    /**
     * Create an instance of {@link WorkflowComponent }
     * 
     */
    public WorkflowComponent createWorkflowComponent() {
        return new WorkflowComponent();
    }

    /**
     * Create an instance of {@link FileTransfer }
     * 
     */
    public FileTransfer createFileTransfer() {
        return new FileTransfer();
    }

    /**
     * Create an instance of {@link Parallel }
     * 
     */
    public Parallel createParallel() {
        return new Parallel();
    }

    /**
     * Create an instance of {@link Transfer }
     * 
     */
    public Transfer createTransfer() {
        return new Transfer();
    }

    /**
     * Create an instance of {@link StageFalure }
     * 
     */
    public StageFalure createStageFalure() {
        return new StageFalure();
    }

    /**
     * Create an instance of {@link ProcessDescriptor }
     * 
     */
    public ProcessDescriptor createProcessDescriptor() {
        return new ProcessDescriptor();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link CallExternalProcess }
     * 
     */
    public CallExternalProcess createCallExternalProcess() {
        return new CallExternalProcess();
    }

    /**
     * Create an instance of {@link PropertyMapping }
     * 
     */
    public PropertyMapping createPropertyMapping() {
        return new PropertyMapping();
    }

    /**
     * Create an instance of {@link NoOpExecDefinition }
     * 
     */
    public NoOpExecDefinition createNoOpExecDefinition() {
        return new NoOpExecDefinition();
    }

    /**
     * Create an instance of {@link ChecksumValidation }
     * 
     */
    public ChecksumValidation createChecksumValidation() {
        return new ChecksumValidation();
    }

    /**
     * Create an instance of {@link CdataProperties }
     * 
     */
    public CdataProperties createCdataProperties() {
        return new CdataProperties();
    }

    /**
     * Create an instance of {@link ChecksumGeneration }
     * 
     */
    public ChecksumGeneration createChecksumGeneration() {
        return new ChecksumGeneration();
    }

    /**
     * Create an instance of {@link SqlLoader }
     * 
     */
    public SqlLoader createSqlLoader() {
        return new SqlLoader();
    }

    /**
     * Create an instance of {@link Variable }
     * 
     */
    public Variable createVariable() {
        return new Variable();
    }

    /**
     * Create an instance of {@link WorkflowRefInputProperties }
     * 
     */
    public WorkflowRefInputProperties createWorkflowRefInputProperties() {
        return new WorkflowRefInputProperties();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link WorkflowProperty }
     * 
     */
    public WorkflowProperty createWorkflowProperty() {
        return new WorkflowProperty();
    }

    /**
     * Create an instance of {@link DbFunction.In }
     * 
     */
    public DbFunction.In createDbFunctionIn() {
        return new DbFunction.In();
    }

    /**
     * Create an instance of {@link DbProcedure.In }
     * 
     */
    public DbProcedure.In createDbProcedureIn() {
        return new DbProcedure.In();
    }

    /**
     * Create an instance of {@link DbProcedure.Out }
     * 
     */
    public DbProcedure.Out createDbProcedureOut() {
        return new DbProcedure.Out();
    }

    /**
     * Create an instance of {@link WorkflowDefinition.WorkflowComponents }
     * 
     */
    public WorkflowDefinition.WorkflowComponents createWorkflowDefinitionWorkflowComponents() {
        return new WorkflowDefinition.WorkflowComponents();
    }

    /**
     * Create an instance of {@link WorkflowProperties.InputProperties }
     * 
     */
    public WorkflowProperties.InputProperties createWorkflowPropertiesInputProperties() {
        return new WorkflowProperties.InputProperties();
    }

    /**
     * Create an instance of {@link WorkflowProperties.GeneralProperties }
     * 
     */
    public WorkflowProperties.GeneralProperties createWorkflowPropertiesGeneralProperties() {
        return new WorkflowProperties.GeneralProperties();
    }

    /**
     * Create an instance of {@link WorkflowProperties.OutputProperties }
     * 
     */
    public WorkflowProperties.OutputProperties createWorkflowPropertiesOutputProperties() {
        return new WorkflowProperties.OutputProperties();
    }

    /**
     * Create an instance of {@link SimpleProperties.Properties }
     * 
     */
    public SimpleProperties.Properties createSimplePropertiesProperties() {
        return new SimpleProperties.Properties();
    }

    /**
     * Create an instance of {@link ExternalWorkflowReference.InputProperties }
     * 
     */
    public ExternalWorkflowReference.InputProperties createExternalWorkflowReferenceInputProperties() {
        return new ExternalWorkflowReference.InputProperties();
    }

    /**
     * Create an instance of {@link PollingFileWatcher.WatchedFiles }
     * 
     */
    public PollingFileWatcher.WatchedFiles createPollingFileWatcherWatchedFiles() {
        return new PollingFileWatcher.WatchedFiles();
    }

    /**
     * Create an instance of {@link CallActiviti.Variables }
     * 
     */
    public CallActiviti.Variables createCallActivitiVariables() {
        return new CallActiviti.Variables();
    }

    /**
     * Create an instance of {@link CallActiviti.OutputProperties }
     * 
     */
    public CallActiviti.OutputProperties createCallActivitiOutputProperties() {
        return new CallActiviti.OutputProperties();
    }

    /**
     * Create an instance of {@link JavaExtension.JavaExtensionOutputPropertyNames }
     * 
     */
    public JavaExtension.JavaExtensionOutputPropertyNames createJavaExtensionJavaExtensionOutputPropertyNames() {
        return new JavaExtension.JavaExtensionOutputPropertyNames();
    }

    /**
     * Create an instance of {@link ComponentReference.InputProperties }
     * 
     */
    public ComponentReference.InputProperties createComponentReferenceInputProperties() {
        return new ComponentReference.InputProperties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "componentReference")
    public JAXBElement<ComponentReference> createComponentReference(ComponentReference value) {
        return new JAXBElement<ComponentReference>(_ComponentReference_QNAME, ComponentReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AutoRetryConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "autoRetryConfiguration")
    public JAXBElement<AutoRetryConfiguration> createAutoRetryConfiguration(AutoRetryConfiguration value) {
        return new JAXBElement<AutoRetryConfiguration>(_AutoRetryConfiguration_QNAME, AutoRetryConfiguration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteResource")
    public JAXBElement<DeleteResource> createDeleteResource(DeleteResource value) {
        return new JAXBElement<DeleteResource>(_DeleteResource_QNAME, DeleteResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JavaExtension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "javaExtension")
    public JAXBElement<JavaExtension> createJavaExtension(JavaExtension value) {
        return new JAXBElement<JavaExtension>(_JavaExtension_QNAME, JavaExtension.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Param }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "param")
    public JAXBElement<Param> createParam(Param value) {
        return new JAXBElement<Param>(_Param_QNAME, Param.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallActiviti }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "callActiviti")
    public JAXBElement<CallActiviti> createCallActiviti(CallActiviti value) {
        return new JAXBElement<CallActiviti>(_CallActiviti_QNAME, CallActiviti.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleProperty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "simpleProperty")
    public JAXBElement<SimpleProperty> createSimpleProperty(SimpleProperty value) {
        return new JAXBElement<SimpleProperty>(_SimpleProperty_QNAME, SimpleProperty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mapping")
    public JAXBElement<Mapping> createMapping(Mapping value) {
        return new JAXBElement<Mapping>(_Mapping_QNAME, Mapping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "execDefinition")
    public JAXBElement<ExecDefinition> createExecDefinition(ExecDefinition value) {
        return new JAXBElement<ExecDefinition>(_ExecDefinition_QNAME, ExecDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Stage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stage")
    public JAXBElement<Stage> createStage(Stage value) {
        return new JAXBElement<Stage>(_Stage_QNAME, Stage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sequential }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sequential")
    public JAXBElement<Sequential> createSequential(Sequential value) {
        return new JAXBElement<Sequential>(_Sequential_QNAME, Sequential.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowComponent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "workflowComponent")
    public JAXBElement<WorkflowComponent> createWorkflowComponent(WorkflowComponent value) {
        return new JAXBElement<WorkflowComponent>(_WorkflowComponent_QNAME, WorkflowComponent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PollingFileWatcher }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pollingFileWatcher")
    public JAXBElement<PollingFileWatcher> createPollingFileWatcher(PollingFileWatcher value) {
        return new JAXBElement<PollingFileWatcher>(_PollingFileWatcher_QNAME, PollingFileWatcher.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalWorkflowReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "externalWorkflowReference")
    public JAXBElement<ExternalWorkflowReference> createExternalWorkflowReference(ExternalWorkflowReference value) {
        return new JAXBElement<ExternalWorkflowReference>(_ExternalWorkflowReference_QNAME, ExternalWorkflowReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "processDefinitionId")
    public JAXBElement<String> createProcessDefinitionId(String value) {
        return new JAXBElement<String>(_ProcessDefinitionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileTransfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileTransfer")
    public JAXBElement<FileTransfer> createFileTransfer(FileTransfer value) {
        return new JAXBElement<FileTransfer>(_FileTransfer_QNAME, FileTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "simpleProperties")
    public JAXBElement<SimpleProperties> createSimpleProperties(SimpleProperties value) {
        return new JAXBElement<SimpleProperties>(_SimpleProperties_QNAME, SimpleProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parallel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parallel")
    public JAXBElement<Parallel> createParallel(Parallel value) {
        return new JAXBElement<Parallel>(_Parallel_QNAME, Parallel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transfer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transfer")
    public JAXBElement<Transfer> createTransfer(Transfer value) {
        return new JAXBElement<Transfer>(_Transfer_QNAME, Transfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StageFalure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stageFailure")
    public JAXBElement<StageFalure> createStageFailure(StageFalure value) {
        return new JAXBElement<StageFalure>(_StageFailure_QNAME, StageFalure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessDescriptor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "processDescriptor")
    public JAXBElement<ProcessDescriptor> createProcessDescriptor(ProcessDescriptor value) {
        return new JAXBElement<ProcessDescriptor>(_ProcessDescriptor_QNAME, ProcessDescriptor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resource")
    public JAXBElement<Resource> createResource(Resource value) {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallExternalProcess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "callExternalProcess")
    public JAXBElement<CallExternalProcess> createCallExternalProcess(CallExternalProcess value) {
        return new JAXBElement<CallExternalProcess>(_CallExternalProcess_QNAME, CallExternalProcess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyMapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "propertyMapping")
    public JAXBElement<PropertyMapping> createPropertyMapping(PropertyMapping value) {
        return new JAXBElement<PropertyMapping>(_PropertyMapping_QNAME, PropertyMapping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "property")
    public JAXBElement<Object> createProperty(Object value) {
        return new JAXBElement<Object>(_Property_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NoOpExecDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "noOpExecDefinition")
    public JAXBElement<NoOpExecDefinition> createNoOpExecDefinition(NoOpExecDefinition value) {
        return new JAXBElement<NoOpExecDefinition>(_NoOpExecDefinition_QNAME, NoOpExecDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "properties")
    public JAXBElement<WorkflowProperties> createProperties(WorkflowProperties value) {
        return new JAXBElement<WorkflowProperties>(_Properties_QNAME, WorkflowProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumValidation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "checksumValidation")
    public JAXBElement<ChecksumValidation> createChecksumValidation(ChecksumValidation value) {
        return new JAXBElement<ChecksumValidation>(_ChecksumValidation_QNAME, ChecksumValidation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "workflow")
    public JAXBElement<WorkflowDefinition> createWorkflow(WorkflowDefinition value) {
        return new JAXBElement<WorkflowDefinition>(_Workflow_QNAME, WorkflowDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CdataProperties }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cdataProperties")
    public JAXBElement<CdataProperties> createCdataProperties(CdataProperties value) {
        return new JAXBElement<CdataProperties>(_CdataProperties_QNAME, CdataProperties.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumGeneration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "checksumGeneration")
    public JAXBElement<ChecksumGeneration> createChecksumGeneration(ChecksumGeneration value) {
        return new JAXBElement<ChecksumGeneration>(_ChecksumGeneration_QNAME, ChecksumGeneration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SqlLoader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sqlLoader")
    public JAXBElement<SqlLoader> createSqlLoader(SqlLoader value) {
        return new JAXBElement<SqlLoader>(_SqlLoader_QNAME, SqlLoader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DbProcedure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dbProcedure")
    public JAXBElement<DbProcedure> createDbProcedure(DbProcedure value) {
        return new JAXBElement<DbProcedure>(_DbProcedure_QNAME, DbProcedure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DbFunction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dbFunction")
    public JAXBElement<DbFunction> createDbFunction(DbFunction value) {
        return new JAXBElement<DbFunction>(_DbFunction_QNAME, DbFunction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Variable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "variable")
    public JAXBElement<Variable> createVariable(Variable value) {
        return new JAXBElement<Variable>(_Variable_QNAME, Variable.class, null, value);
    }

}
