//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Execution Definition for a Polling File Watcher.  This will monitor the filesystem for the specified files, and succeed if the files are found or fail if they are missing.
 * 
 * <p>Java class for pollingFileWatcher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pollingFileWatcher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="watchedFiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}resource" maxOccurs="99"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="matchedCountProperty">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="allowFileNotFound" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pollingFileWatcher", propOrder = {
    "watchedFiles",
    "matchedCountProperty",
    "allowFileNotFound"
})
public class PollingFileWatcher {

    @XmlElement(required = true)
    protected PollingFileWatcher.WatchedFiles watchedFiles;
    @XmlElement(required = true)
    protected String matchedCountProperty;
    protected Boolean allowFileNotFound;

    /**
     * Gets the value of the watchedFiles property.
     * 
     * @return
     *     possible object is
     *     {@link PollingFileWatcher.WatchedFiles }
     *     
     */
    public PollingFileWatcher.WatchedFiles getWatchedFiles() {
        return watchedFiles;
    }

    /**
     * Sets the value of the watchedFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link PollingFileWatcher.WatchedFiles }
     *     
     */
    public void setWatchedFiles(PollingFileWatcher.WatchedFiles value) {
        this.watchedFiles = value;
    }

    /**
     * Gets the value of the matchedCountProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchedCountProperty() {
        return matchedCountProperty;
    }

    /**
     * Sets the value of the matchedCountProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchedCountProperty(String value) {
        this.matchedCountProperty = value;
    }

    /**
     * Gets the value of the allowFileNotFound property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowFileNotFound() {
        return allowFileNotFound;
    }

    /**
     * Sets the value of the allowFileNotFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowFileNotFound(Boolean value) {
        this.allowFileNotFound = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}resource" maxOccurs="99"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resource"
    })
    public static class WatchedFiles {

        @XmlElement(required = true)
        protected List<Resource> resource;

        /**
         * File Resource to watch.  Can be a local or remote file, or regular expression pattern for matching a local or remote file.Gets the value of the resource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Resource }
         * 
         * 
         */
        public List<Resource> getResource() {
            if (resource == null) {
                resource = new ArrayList<Resource>();
            }
            return this.resource;
        }

    }

}
