//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for propertyValueTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="propertyValueTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="LONG"/>
 *     &lt;enumeration value="BIG_DECIMAL"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="SHORT"/>
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="ASSET_ID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "propertyValueTypeEnum")
@XmlEnum
public enum PropertyValueTypeEnum {

    STRING,
    DATE,
    LONG,
    BIG_DECIMAL,
    INTEGER,
    SHORT,
    BOOLEAN,
    ASSET_ID;

    public String value() {
        return name();
    }

    public static PropertyValueTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
