//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A sequential stage group in the workflow definition.
 * 
 * <p>Java class for sequential complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sequential">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="skipCondition" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}stageFailure" minOccurs="0"/>
 *         &lt;choice maxOccurs="99">
 *           &lt;element ref="{}stage"/>
 *           &lt;element ref="{}componentReference"/>
 *           &lt;element ref="{}externalWorkflowReference"/>
 *           &lt;element ref="{}parallel"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}ID">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sequential", propOrder = {
    "skipCondition",
    "stageFailure",
    "stageOrComponentReferenceOrExternalWorkflowReference"
})
public class Sequential {

    protected String skipCondition;
    protected StageFalure stageFailure;
    @XmlElements({
        @XmlElement(name = "stage", type = Stage.class),
        @XmlElement(name = "componentReference", type = ComponentReference.class),
        @XmlElement(name = "externalWorkflowReference", type = ExternalWorkflowReference.class),
        @XmlElement(name = "parallel", type = Parallel.class)
    })
    protected List<Object> stageOrComponentReferenceOrExternalWorkflowReference;
    @XmlAttribute(name = "enabled")
    protected Boolean enabled = true;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the skipCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkipCondition() {
        return skipCondition;
    }

    /**
     * Sets the value of the skipCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkipCondition(String value) {
        this.skipCondition = value;
    }

    /**
     * Failure Condition.  This branch of Workflow execution will fail if this condition evaluates to 'true'.  Is evaluated after the branch finishes executing.
     * 
     * @return
     *     possible object is
     *     {@link StageFalure }
     *     
     */
    public StageFalure getStageFailure() {
        return stageFailure;
    }

    /**
     * Sets the value of the stageFailure property.
     * 
     * @param value
     *     allowed object is
     *     {@link StageFalure }
     *     
     */
    public void setStageFailure(StageFalure value) {
        this.stageFailure = value;
    }

    /**
     * Gets the value of the stageOrComponentReferenceOrExternalWorkflowReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stageOrComponentReferenceOrExternalWorkflowReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStageOrComponentReferenceOrExternalWorkflowReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stage }
     * {@link ComponentReference }
     * {@link ExternalWorkflowReference }
     * {@link Parallel }
     * 
     * 
     */
    public List<Object> getStageOrComponentReferenceOrExternalWorkflowReference() {
        if (stageOrComponentReferenceOrExternalWorkflowReference == null) {
            stageOrComponentReferenceOrExternalWorkflowReference = new ArrayList<Object>();
        }
        return this.stageOrComponentReferenceOrExternalWorkflowReference;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
