//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Execution Definition which loads bulk data using Oracle SQL*Loader.
 * 
 * <p>Java class for sqlLoader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sqlLoader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="controlFileUri">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dataFileUri" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="discardFileUri">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rejectFileUri">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="logFileUri">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1024"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exitCodeProperty">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfRejectedRowsProperty">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfDiscardedRowsProperty">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sqlLoader", propOrder = {
    "controlFileUri",
    "dataFileUri",
    "discardFileUri",
    "rejectFileUri",
    "logFileUri",
    "exitCodeProperty",
    "numberOfRejectedRowsProperty",
    "numberOfDiscardedRowsProperty"
})
public class SqlLoader {

    @XmlElement(required = true)
    protected String controlFileUri;
    protected String dataFileUri;
    @XmlElement(required = true)
    protected String discardFileUri;
    @XmlElement(required = true)
    protected String rejectFileUri;
    @XmlElement(required = true)
    protected String logFileUri;
    @XmlElement(required = true)
    protected String exitCodeProperty;
    @XmlElement(required = true)
    protected String numberOfRejectedRowsProperty;
    @XmlElement(required = true)
    protected String numberOfDiscardedRowsProperty;

    /**
     * Gets the value of the controlFileUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlFileUri() {
        return controlFileUri;
    }

    /**
     * Sets the value of the controlFileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlFileUri(String value) {
        this.controlFileUri = value;
    }

    /**
     * Gets the value of the dataFileUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFileUri() {
        return dataFileUri;
    }

    /**
     * Sets the value of the dataFileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFileUri(String value) {
        this.dataFileUri = value;
    }

    /**
     * Gets the value of the discardFileUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscardFileUri() {
        return discardFileUri;
    }

    /**
     * Sets the value of the discardFileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscardFileUri(String value) {
        this.discardFileUri = value;
    }

    /**
     * Gets the value of the rejectFileUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRejectFileUri() {
        return rejectFileUri;
    }

    /**
     * Sets the value of the rejectFileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRejectFileUri(String value) {
        this.rejectFileUri = value;
    }

    /**
     * Gets the value of the logFileUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileUri() {
        return logFileUri;
    }

    /**
     * Sets the value of the logFileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileUri(String value) {
        this.logFileUri = value;
    }

    /**
     * Gets the value of the exitCodeProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitCodeProperty() {
        return exitCodeProperty;
    }

    /**
     * Sets the value of the exitCodeProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitCodeProperty(String value) {
        this.exitCodeProperty = value;
    }

    /**
     * Gets the value of the numberOfRejectedRowsProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfRejectedRowsProperty() {
        return numberOfRejectedRowsProperty;
    }

    /**
     * Sets the value of the numberOfRejectedRowsProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfRejectedRowsProperty(String value) {
        this.numberOfRejectedRowsProperty = value;
    }

    /**
     * Gets the value of the numberOfDiscardedRowsProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfDiscardedRowsProperty() {
        return numberOfDiscardedRowsProperty;
    }

    /**
     * Sets the value of the numberOfDiscardedRowsProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfDiscardedRowsProperty(String value) {
        this.numberOfDiscardedRowsProperty = value;
    }

}
