//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * A Workflow Component is a re-usable set of Workflow Stages which can be referenced multiple times throughout a total Maestro Workflow.  Workflow Components are referenced by their id.  Workflow Components can be parameterized by using the Workflow Component Input Properties. Output parameters can be passed to the calling Workflow context using the Workflow Component Output Parameters.
 * 
 * <p>Java class for workflowComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workflowComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}properties" minOccurs="0"/>
 *         &lt;choice maxOccurs="99">
 *           &lt;element ref="{}parallel"/>
 *           &lt;element ref="{}sequential"/>
 *           &lt;element ref="{}stage"/>
 *           &lt;element ref="{}externalWorkflowReference"/>
 *           &lt;element ref="{}componentReference"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workflowComponent", propOrder = {
    "properties",
    "parallelOrSequentialOrStage"
})
public class WorkflowComponent {

    protected WorkflowProperties properties;
    @XmlElements({
        @XmlElement(name = "parallel", type = Parallel.class),
        @XmlElement(name = "sequential", type = Sequential.class),
        @XmlElement(name = "stage", type = Stage.class),
        @XmlElement(name = "externalWorkflowReference", type = ExternalWorkflowReference.class),
        @XmlElement(name = "componentReference", type = ComponentReference.class)
    })
    protected List<Object> parallelOrSequentialOrStage;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowProperties }
     *     
     */
    public WorkflowProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowProperties }
     *     
     */
    public void setProperties(WorkflowProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the parallelOrSequentialOrStage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parallelOrSequentialOrStage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParallelOrSequentialOrStage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parallel }
     * {@link Sequential }
     * {@link Stage }
     * {@link ExternalWorkflowReference }
     * {@link ComponentReference }
     * 
     * 
     */
    public List<Object> getParallelOrSequentialOrStage() {
        if (parallelOrSequentialOrStage == null) {
            parallelOrSequentialOrStage = new ArrayList<Object>();
        }
        return this.parallelOrSequentialOrStage;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
