//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 01:59:20 PM EDT 
//


package ca.mss.rd.wkfdef.iw;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A workflow definition.
 * 
 * <p>Java class for workflowDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workflowDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="externalWorkflowCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="128"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="finishOrchestrationASAPOnError" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="description" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{}properties" minOccurs="0"/>
 *         &lt;element name="workflowComponents" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}workflowComponent" maxOccurs="99" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element ref="{}stage"/>
 *           &lt;element ref="{}componentReference"/>
 *           &lt;element ref="{}externalWorkflowReference"/>
 *           &lt;element ref="{}sequential"/>
 *           &lt;element ref="{}parallel"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workflowDefinition", propOrder = {
    "name",
    "externalWorkflowCode",
    "finishOrchestrationASAPOnError",
    "description",
    "properties",
    "workflowComponents",
    "stage",
    "componentReference",
    "externalWorkflowReference",
    "sequential",
    "parallel"
})

@XmlRootElement(name="workflow")
public class WorkflowDefinition {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String externalWorkflowCode;
    protected boolean finishOrchestrationASAPOnError;
    protected String description;
    protected WorkflowProperties properties;
    protected WorkflowDefinition.WorkflowComponents workflowComponents;
    protected Stage stage;
    protected ComponentReference componentReference;
    protected ExternalWorkflowReference externalWorkflowReference;
    protected Sequential sequential;
    protected Parallel parallel;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the externalWorkflowCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalWorkflowCode() {
        return externalWorkflowCode;
    }

    /**
     * Sets the value of the externalWorkflowCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalWorkflowCode(String value) {
        this.externalWorkflowCode = value;
    }

    /**
     * Gets the value of the finishOrchestrationASAPOnError property.
     * 
     */
    public boolean isFinishOrchestrationASAPOnError() {
        return finishOrchestrationASAPOnError;
    }

    /**
     * Sets the value of the finishOrchestrationASAPOnError property.
     * 
     */
    public void setFinishOrchestrationASAPOnError(boolean value) {
        this.finishOrchestrationASAPOnError = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowProperties }
     *     
     */
    public WorkflowProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowProperties }
     *     
     */
    public void setProperties(WorkflowProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the workflowComponents property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowDefinition.WorkflowComponents }
     *     
     */
    public WorkflowDefinition.WorkflowComponents getWorkflowComponents() {
        return workflowComponents;
    }

    /**
     * Sets the value of the workflowComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowDefinition.WorkflowComponents }
     *     
     */
    public void setWorkflowComponents(WorkflowDefinition.WorkflowComponents value) {
        this.workflowComponents = value;
    }

    /**
     * Gets the value of the stage property.
     * 
     * @return
     *     possible object is
     *     {@link Stage }
     *     
     */
    public Stage getStage() {
        return stage;
    }

    /**
     * Sets the value of the stage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stage }
     *     
     */
    public void setStage(Stage value) {
        this.stage = value;
    }

    /**
     * Gets the value of the componentReference property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentReference }
     *     
     */
    public ComponentReference getComponentReference() {
        return componentReference;
    }

    /**
     * Sets the value of the componentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentReference }
     *     
     */
    public void setComponentReference(ComponentReference value) {
        this.componentReference = value;
    }

    /**
     * Gets the value of the externalWorkflowReference property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalWorkflowReference }
     *     
     */
    public ExternalWorkflowReference getExternalWorkflowReference() {
        return externalWorkflowReference;
    }

    /**
     * Sets the value of the externalWorkflowReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalWorkflowReference }
     *     
     */
    public void setExternalWorkflowReference(ExternalWorkflowReference value) {
        this.externalWorkflowReference = value;
    }

    /**
     * Gets the value of the sequential property.
     * 
     * @return
     *     possible object is
     *     {@link Sequential }
     *     
     */
    public Sequential getSequential() {
        return sequential;
    }

    /**
     * Sets the value of the sequential property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sequential }
     *     
     */
    public void setSequential(Sequential value) {
        this.sequential = value;
    }

    /**
     * Gets the value of the parallel property.
     * 
     * @return
     *     possible object is
     *     {@link Parallel }
     *     
     */
    public Parallel getParallel() {
        return parallel;
    }

    /**
     * Sets the value of the parallel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parallel }
     *     
     */
    public void setParallel(Parallel value) {
        this.parallel = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}workflowComponent" maxOccurs="99" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "workflowComponent"
    })
    public static class WorkflowComponents {

        protected List<WorkflowComponent> workflowComponent;

        /**
         * A Workflow Component is a re-usable set of Workflow Stages which can be referenced multiple times throughout a total Maestro Workflow.  Workflow Components are referenced by their id.  Workflow Components can be parameterized by using the Workflow Component Input Properties. Output parameters can be passed to the calling Workflow context using the Workflow Component Output Parameters.Gets the value of the workflowComponent property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the workflowComponent property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWorkflowComponent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WorkflowComponent }
         * 
         * 
         */
        public List<WorkflowComponent> getWorkflowComponent() {
            if (workflowComponent == null) {
                workflowComponent = new ArrayList<WorkflowComponent>();
            }
            return this.workflowComponent;
        }

    }

}
